name: Compilar Car Launcher

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Reparar Motor Gradle
      run: gradle wrapper --gradle-version 8.7
        
    - name: Compilar APK
      # Definimos la variable MAPS_API_KEY para que el Manifest la recoja. 
      # Si está vacía, Google Maps compilará pero mostrará una marca de agua de desarrollo.
      env:
        MAPS_API_KEY: "" 
      run: |
        chmod +x gradlew
        ./gradlew :app:assembleDebug
        
    - name: Subir APK
      uses: actions/upload-artifact@v4
      with:
        name: CarLauncher-APK
        path: app/build/outputs/apk/debug/app-debug.apk